### ISSUE TITLE
sigmaEOverE smearing returns inf

### ISSUE THREAD

**Issue by sethzenz** [cms-analysis/flashgg#1011]
Since #1006 the sigmaEOverE smearing is somehow looking up "inf" for the per-photonresolution, which is then propagated through the central MC resolution and gives infinite-energy photon, which obviously produces surprising results downstream.

I am still checking for how it's happening in detail but here are instructions to reproduce with the current flashgg master:

1. Change the debug to True on this line:

https://github.com/cms-analysis/flashgg/blob/754c8fccb772f025bbc50e6dfa87e05f8d9f79f1/Systematics/python/flashggDiPhotonSystematics_cfi.py#L634

And also on this line:

https://github.com/cms-analysis/flashgg/blob/754c8fccb772f025bbc50e6dfa87e05f8d9f79f1/Systematics/python/flashggDiPhotonSystematics_cfi.py#L709

[and possibly for the 3 other R9 EB/EE combinations]

2. Run the following:

cmsRun Systematics/test/workspaceStd.py doHTXS=1

You will then see error messages like I have...

```
  SigmaEOverESmearing: Photon has pt= 125.474 eta=-0.911612 full5x5_r9=0.949476 and we apply a sigmaEoverE smearing of inf

     sigE/E VALUE BEFORE: 0.00502538

     sigE/E VALUE AFTER: inf

START OF DiPhotonFromPhoton::applyCorrection M PT E1 E2 ETA1 ETA2 160.308 104.375 182.969 35.7221 -0.924076 0.998463

  MCSmearHighR9EBCentral: Photon has energy= 182.969 eta=-0.924076 and we apply a smearing with sigma inf% to get new energy=-inf
```

**Comment by sethzenz** [comment]
This code will catch the issue, and indeed calls an exception on the very first photon:

```
--- a/Systematics/plugins/PhotonSigEoverESmearingEGMTool.cc
+++ b/Systematics/plugins/PhotonSigEoverESmearingEGMTool.cc
@@ -66,6 +66,10 @@ namespace flashgg {
             // computed by getSmearingSigma(...)
             auto sigma = scaler_.smearingSigma(run_number_, y.et(), y.superCluster()->eta(), y.full5x5_r9(), gain, 0, 0);// never apply systematic shift
 
+            if ( sigma < 0. || sigma > 1. ) {
+                throw cms::Exception("SmearingLogic") << " sigmaEOverE is going to be smeared by " << sigma << " which sounds implausible (allowed: 0-1)";
+            }
+
```

**Comment by shervin86** [comment]
with some couts, here's what is the status:
```START OF DiPhotonFromPhoton::applyCorrection M PT E1 E2 ETA1 ETA2 121.74 33.2007 87.1733 167.212 -0.890571 -1.83128
run: [0 999999] eta: [0 1]      R9: [0.94 3.40282e+38]  Et: [0 1e+07]   gain: 0 does contain run 1 et 61.2399 eta 0.9227 r9 0.952579 gain seed 12
 --> 0.0088 +/- 0.0001  1.5708 +/- 1.5708       6.6 +/- 0
0.0088  1.5708  0.0088  -2.53876e-09 inf
  SigmaEOverESmearing: Photon has pt= 61.2399 eta=-0.9227 full5x5_r9=0.952579 and we apply a sigmaEoverE smearing of inf
```
These are: 
```
rho        phi        cTerm   alpha              sqrt(cTerm * cTerm + alpha * alpha / et)
0.0088  1.5708  0.0088  -2.53876e-09 inf
```
I don't yet understand how is it possible that the sqrt fails
