### ISSUE TITLE
Can't build in 80X

### ISSUE THREAD

**Issue by thongonary** [cms-analysis/flashgg#1077]
I followed the README instruction to install flashgg from scratch for CMSSW_8_0_28; however it failed at the build step:

> Compiling edm plugin /afs/cern.ch/work/q/qnguyen/public/HHbbgg/CMSSW_8_0_28/src/flashgg/Systematics/plugins/PhotonSmearStochasticEGMTool.cc
> /afs/cern.ch/work/q/qnguyen/public/HHbbgg/CMSSW_8_0_28/src/flashgg/Systematics/plugins/PhotonSmearStochasticEGMTool.cc:9:68: fatal error: RecoEgamma/EgammaTools/interface/EnergyScaleCorrection.h: No such file or directory
> compilation terminated.
> /afs/cern.ch/work/q/qnguyen/public/HHbbgg/CMSSW_8_0_28/src/flashgg/Systematics/plugins/PhotonSmearStochasticEGMTool.cc:9:68: fatal error: RecoEgamma/EgammaTools/interface/EnergyScaleCorrection.h: No such file or directory
> compilation terminated.
> config/SCRAM/GMake/Makefile.rules:1937: recipe for target 'tmp/slc6_amd64_gcc530/src/flashgg/Systematics/plugins/FlashggSystematicsPlugins/PhotonSmearStochasticEGMTool.o' failed
> gmake: *** [tmp/slc6_amd64_gcc530/src/flashgg/Systematics/plugins/FlashggSystematicsPlugins/PhotonSmearStochasticEGMTool.o] Error 1
> gmake: *** Waiting for unfinished jobs....
> gmake: *** [There are compilation/build errors. Please see the detail log above.] Error 2
> 

Is there a quick way to fix this?

**Comment by simonepigazzini** [comment]
@thongonary thanks for reporting this. The issue was introduced by this PR:

https://github.com/cms-analysis/flashgg/pull/1006

we are working to fix it in a way that works for both CMSSW_8X and 9X. In the meanwhile you can modify the include statement yourself:

CMSSW_8: "EgammaAnalysis/ElectronTools/interface/EnergyScaleCorrection_class.h
CMSSW_9: "RecoEgamma/EgammaTools/interface/EnergyScaleCorrection.h"

simone

**Comment by thongonary** [comment]
Thanks @simonepigazzini . Just for the record, this commit https://github.com/cms-analysis/flashgg/commit/022c2d60da1cf687720d65acbf5c99f503a58219 also breaks 8_0_28

> Compiling  /afs/cern.ch/work/q/qnguyen/public/HHbbgg/CMSSW_8_0_28/src/flashgg/Taggers/src/TagsDumpers.cc
> In file included from /afs/cern.ch/work/q/qnguyen/public/HHbbgg/CMSSW_8_0_28/src/flashgg/Taggers/interface/TagsDumpers.h:18:0,
>                  from /afs/cern.ch/work/q/qnguyen/public/HHbbgg/CMSSW_8_0_28/src/flashgg/Taggers/src/TagsDumpers.cc:1:
> /afs/cern.ch/work/q/qnguyen/public/HHbbgg/CMSSW_8_0_28/src/flashgg/Taggers/interface/CollectionDumper.h:37:70: fatal error: SimDataFormats/HTXS/interface/HiggsTemplateCrossSections.h: No such file or directory
> compilation terminated.
> In file included from /afs/cern.ch/work/q/qnguyen/public/HHbbgg/CMSSW_8_0_28/src/flashgg/Taggers/interface/TagsDumpers.h:18:0,
>                  from /afs/cern.ch/work/q/qnguyen/public/HHbbgg/CMSSW_8_0_28/src/flashgg/Taggers/src/TagsDumpers.cc:1:
> /afs/cern.ch/work/q/qnguyen/public/HHbbgg/CMSSW_8_0_28/src/flashgg/Taggers/interface/CollectionDumper.h:37:70: fatal error: SimDataFormats/HTXS/interface/HiggsTemplateCrossSections.h: No such file or directory
> compilation terminated.
> config/SCRAM/GMake/Makefile.rules:1937: recipe for target 'tmp/slc6_amd64_gcc530/src/flashgg/Taggers/src/flashggTaggers/TagsDumpers.o' failed
> gmake: *** [tmp/slc6_amd64_gcc530/src/flashgg/Taggers/src/flashggTaggers/TagsDumpers.o] Error 1
> gmake: *** Waiting for unfinished jobs....

**Comment by thongonary** [comment]
Hi,
Just in case it's helpful for someone, I fixed all the incompatibilities to make it runnable in 8_0_28. The branch can be found here:
https://github.com/thongonary/flashgg/tree/worked_8_0_28

**Comment by simonepigazzini** [comment]
The dev_legacy_runII branch is now the recommended branch for legacy RunII analysis.
