### ISSUE TITLE
Tags: sorted collections

### ISSUE THREAD

**Issue by sethzenz** [cms-analysis/flashgg#110]
Set up Tag producers so that tags are organized with operator< automatically from each tag producer.  Use ordered CMSSW collections if possible; check how it's done for PatCandidates.  (Check if this feature simplifies tag sorter logic.)

**Comment by sethzenz** [comment]
Hmm, sorted collection seems to require a key rather than just an operator< implementation.  I wonder if this is worth it..? https://github.com/cms-sw/cmssw/blob/CMSSW_7_4_X/DataFormats/Common/interface/SortedCollection.h

**Comment by sethzenz** [comment]
Unless anyone has any ideas, I think I will close this one.  Things work just fine without this feature now, and I don't think it will save much time in the tag sorter.

**Comment by musella** [comment]
Hi Seth,

I think that using sumpT as the sorting key would work for diphotons.

For the tags something more would be needed to keep more than one family of
tags in the same collection.

I would reopen this issue and implement at least the diphotons sorting.

Cheers,
P.


On 19 January 2015 at 13:26, Seth Zenz <notifications@github.com> wrote:

> Unless anyone has any ideas, I think I will close this one. Things work
> just fine without this feature now, and I don't think it will save much
> time in the tag sorter.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-analysis/flashgg/issues/110#issuecomment-70485419>
> .
>



-- 
Pasquale Musella - ETHZ
http://musella.web.cern.ch/musella
