### ISSUE TITLE
QGTagger implementation

### ISSUE THREAD

**Issue by simonepigazzini** [cms-analysis/flashgg#1102]
Check GTagger recipe used in when building flashggJets in MicroAODs:

https://github.com/cms-analysis/flashgg/blob/dev_legacy_runII/MicroAOD/python/flashggJets_cfi.py

also the whole jet workflow might need a second look to ensure the recipe are up to date with legacy RunII

**Comment by simonepigazzini** [comment]
Priority goes to changes required to produce flashgg::Jets, as any changes to these will require a new microAOD production.

**Comment by edjtscott** [comment]
hi @simonepigazzini, sorry for the delay on this - I am beginning to look into the jets now

**Comment by simonepigazzini** [comment]
Hi Ed, thanks. As we discussed during one of the Hgg meetings please prioritize anything needed for microAOD production, systematics and taggers can come later. 

simone

**Comment by simonepigazzini** [comment]
Fixed by PR #1119.
