### ISSUE TITLE
MetaData scripts completion

### ISSUE THREAD

**Issue by musella** [cms-analysis/flashgg#161]
Opening this issue to make sure we don't forget this.

As they are, MetaData scripts need to be completed to:
- Have ability to resubmit failed jobs.
- Be more accurate at ensuring reproducibility of task running. 
  For the most important jobs we should store tgz with config and libraries and 
  set up scram scratch space at run time (a la crab). 
- Compute per-sample PU distribution and generate PU weights.
- Keep an eye on duty cycle and automatically resubmit stuck jobs to cope 
  with eos shortcomings.
- Define generic batch interface to support on-LSF clusters.
- Use fwk job report to ensure that full dataset was processed

**Comment by sethzenz** [comment]
Also needed: clear error messages when syntax mistakes are made!  Here's a fun one:

```[sethzenz@lxplus0115]/afs/cern.ch/work/s/sethzenz/fromscratch25/CMSSW_7_4_6_patch2/src/flashgg/MetaData% fggManageSamples.py -C RunIISpring15-50ns -v Spring15BetaV4 import
Will use the following datasets catalog:
/afs/cern.ch/work/s/sethzenz/fromscratch25/CMSSW_7_4_6_patch2/src/flashgg/MetaData/data/RunIISpring15-50ns/datasets.json
Traceback (most recent call last):
  File "/afs/cern.ch/work/s/sethzenz/fromscratch25/CMSSW_7_4_6_patch2/bin/slc6_amd64_gcc491/fggManageSamples.py", line 7, in <module>
    run()
  File "/afs/cern.ch/work/s/sethzenz/fromscratch25/CMSSW_7_4_6_patch2/python/flashgg/MetaData/samples_utils.py", line 627, in __call__
    sys.exit("Unkown command %s" % a)
NameError: global name 'a' is not defined```
