### ISSUE TITLE
Migrate to 73X

### ISSUE THREAD

**Issue by sethzenz** [cms-analysis/flashgg#163]
It appears that CMSSW_7_3_2 is a sufficiently stable migration target.  However, some of the effort (e.g. on jet tools) is non-trivial.  I propose we do this after the Higgs Workshop to avoid confusion.

**Comment by sethzenz** [comment]
We ended up going to CMSSW_7_4_0_pre9

**Comment by musella** [comment]
Hi,

sorry to reply after this has been closed, but I think that passing
edm::Handles around in interfaces is not a good practice, especially if
they are not const.

This makes the code tight to the fact that objects are read/written in the
event, while this may not necessarily be the case.

I would rather suggest that PtrVectors are replaced with const vector<Ptr>
in interfaces.
At most, one should pass direcly Views around.

Cheers,
Pasquale





On 26 March 2015 at 16:34, Seth Zenz <notifications@github.com> wrote:

> Closed #163 <https://github.com/cms-analysis/flashgg/issues/163>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-analysis/flashgg/issues/163#event-265991405>.
>



-- 
Pasquale Musella - ETHZ
http://musella.web.cern.ch/musella

**Comment by sethzenz** [comment]
Yes, I agree with this.  At first we didn't realize that vector<Ptr> was an option even though PtrVector no longer is, but we should still go back and keep the Handles out of the interfaces.  I've created #202 for this issue.
