### ISSUE TITLE
Add functionality to histograms filling in dumper

### ISSUE THREAD

**Issue by matteosan1** [cms-analysis/flashgg#178]
Add the possibility to fill a single histograms with more than 1 input variable e.g.
"subIDMVA,leadIDMV>>idmva(100,-0.3, 0.6)"

**Comment by musella** [comment]
Addressed by #313.

Histograms can now be filled an arbitrary number of times. Actually implemented syntax is two repeat histogram declaration several times:
"leadIDMVA>>idmva(100,-0.3, 0.6)",
"subIDMVA>>idmva(100,-0.3, 0.6)"
