### ISSUE TITLE
"Reroute" diphoton processing in tag step

### ISSUE THREAD

**Issue by sethzenz** [cms-analysis/flashgg#181]
The default tag sequence currently uses the DiPhotonCollection directly as input.  I propose to switch it to start with the preselectedDiPhotonCollection and use the central value of the new systematics producer.  This should not have any drastic downstream effects, and has to be done anyway, but I will check that the tag output is more or less the same.  Any other comments/concerns?

**Comment by musella** [comment]
Hi,

I disagree. The preselection has not been tuned for run II conditions, so I
would not switch until this has been done.

If you want to take the formal action of changing the input name, I would
suggest to remove any selection from the preselectedDiPhotons such that
they become identical to the diphotons.

Cheers,
Pasquale

On 4 March 2015 at 11:07, Seth Zenz <notifications@github.com> wrote:

> The default tag sequence currently uses the DiPhotonCollection directly as
> input. I propose to switch it to start with the
> preselectedDiPhotonCollection and use the central value of the new
> systematics producer. This should not have any drastic downstream effects,
> and has to be done anyway, but I will check that the tag output is more or
> less the same. Any other comments/concerns?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-analysis/flashgg/issues/181>.
>



-- 
Pasquale Musella - ETHZ
http://musella.web.cern.ch/musella

**Comment by sethzenz** [comment]
I want to have the preselection module in the routine tests more than anything.  Maybe I'll just put in a preselection that does the photon eta cuts?  I don't think these are done anywhere at the moment -- not even in the full preselection module -- and I think the preselection is the right place?
