### ISSUE TITLE
Some flashgg::Photon methods/data members shadow pat::Photon ones

### ISSUE THREAD

**Issue by musella** [cms-analysis/flashgg#194]
In particular those related to regression inputs:

https://github.com/cms-analysis/flashgg/blob/master/DataFormats/interface/Photon.h#L25

http://cmslxr.fnal.gov/lxr/source/DataFormats/PatCandidates/interface/Photon.h#0234

Also, in the case where the methods are not explicitely shadowed, we end up generating confusion on which method is being called.

I would suggest to add a "fgg" prefix (or similar) to both the data member name and the getters/setters.

**Comment by ferriff** [comment]
Can't we reuse the same members instead of sort of duplicating the
information? Is there a reason to keep both (besides the possibility to
make comparisons)?
Federico

**Comment by musella** [comment]
I guess we can. I guess that there is no real reason for duplicating the variables.

One feature that we would like to keep is the ability to be able to recompute those variables on the fly (to cope with possible MINIAOD bugs).

This would imply changing the code in PhotonIdUtils such that the pat::Photon members are set in this recomputation.

I would suggest a two step approach though: 
- we first make a pr with the renaming;
- then we remove duplicates and change photonid code.

The second step will also make the data fromat not backward compatible. I am not completely sure of how to deal with it.

**Comment by ferriff** [comment]
Mmmhhh... I am missing something: if we remove the duplicates, why do
we need the renaming then?
Federico
