### ISSUE TITLE
prepareCrabJobs.py

### ISSUE THREAD

**Issue by mdonega** [cms-analysis/flashgg#241]
flashgg/MetaData/work/prepareCrabJobs.py

108 if options.dumpCfg:
109    print ( dumpCfg(cfg) )
110    exit(0)

it should be:
109    print ( dumpCfg(options) )

**Comment by musella** [comment]
This is intended to be like this: if run with the dumpCfg option a json structure containing all options is printed to the screen but the excecution is stopped.
