### ISSUE TITLE
./prepareCrabJobs.py --load <previous_config.json>

### ISSUE THREAD

**Issue by mdonega** [cms-analysis/flashgg#242]
The "--load" features doesn't work because of two bugs in optpars_utils.py

The first one is:
L32        if origin:
L33           origin += ",%s",value

should be

L32        if origin:
L33            origin += " "
L34            origin += ''.join(value)

The second is:
L50                if attr and type(attr) == list:           
L51                    attr.extend(v)
L52                setter(dest,k,v)

L50               if attr and type(attr) == list:
L51                    attr.extend(v)
L52                    setter(dest,k,attr)                                                                                                                                                                                       
L53                else:
L54                    setter(dest,k,v)

**Comment by musella** [comment]
Indeed this should be fixed, though they only affect the instances where `--load` is called multiple times.

For the first part, it should simply be ` origin += ",%s",value`. For the second one, the proposal is fine.

@mdonega can you please make a PR? 

Thanks
