### ISSUE TITLE
Reduce size of PileupSummaryInfos

### ISSUE THREAD

**Issue by sethzenz** [cms-analysis/flashgg#269]
Currently PileupSummaryInfos_addPileupInfo takes up the second-largest amount of space in the expanded MicroAOD:

File file:myMicroAODOutputFile.root Events 259
Branch Name | Average Uncompressed Size (Bytes/Event) | Average Compressed Size (Bytes/Event) 
flashggJets_flashggJets__FLASHggMicroAOD. 76707.5 9590.08
PileupSummaryInfos_addPileupInfo__HLT. 14749.1 5354.72

TODO: filter or otherwise reduce the size of this collection

**Comment by bendavid** [comment]
Not sure how much you guys discussed this.  Full details are stored for all 16 bunch crossings in the mixing.

Good compromise might be to store full details for bx=0, plus just the number of pileup interactions (true and observed) for the other bunch crossings.

I would say this is a candidate for miniaod itself even.

**Comment by bendavid** [comment]
Minimal implementation I can think of would be a slimmer which just zeros the vectors in all the PileupSummary objects not corresponding to bx=0.

**Comment by bendavid** [comment]
What sample are you looking at though?

Looking at a 25ns run 2 ttbar sample I see
Branch Name | Average Uncompressed Size (Bytes/Event) | Average Compressed Size (Bytes/Event)
PileupSummaryInfos_addPileupInfo__HLT. 7388.38 2171.41

Is this PU50 25ns or something?

**Comment by bendavid** [comment]
@gpetruc this could still save probably 2kb per event.  (And I don't see why anyone would need the detailed info for the out of time bunches.)

**Comment by gpetruc** [comment]
yes, the compromize you propose (store full details for bx=0, plus just the number of pileup interactions (true and observed) for the other bunch crossings) would probably be good for miniAOD too.
A PR of a slimmer for 75X would be welcome

**Comment by sethzenz** [comment]
@bendavid - yes, this is a slightly old 25ns RelVal: /store/relval/CMSSW_7_4_0_pre9/RelValH130GGgluonfusion_13/MINIAODSIM/PU25ns_MCRUN2_74_V7-v1/00000/5ABC049C-4CD4-E411-B28A-0025905A613C.root

**Comment by bendavid** [comment]
@lgray

**Comment by lgray** [comment]
```
lgray@lxplus0066:~/work/public/CMSSW_7_4_7_patch2/src/matrix_tests/25202.0_TTbar_13+TTbar_13INPUT+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25+MINIAODMCUP15 > $ !edmEventSize
edmEventSize -a -v step5.root | grep PileupSummary
Warning in <TClass::Init>: no dictionary for class edm::AtomicPtrCache<vector<edm::Ptr<CaloTower> > > is available
PileupSummaryInfos_addPileupInfo__HLT. 15015.2 4917.57
PileupSummaryInfos_slimmedAddPileupInfo__PAT. 1889.41 485.25
```

Here's the producer:
https://github.com/lgray/cmssw/blob/458579a079c06798fc72141d5522fb13367137b4/PhysicsTools/PatAlgos/plugins/PileupSummaryInfoSlimmer.cc

Here's the config (that gets the above numbers):
https://github.com/lgray/cmssw/blob/458579a079c06798fc72141d5522fb13367137b4/PhysicsTools/PatAlgos/python/slimming/slimmedAddPileupInfo_cfi.py

**Comment by lgray** [comment]
@musella factor of 10, going to submit this to MiniAOD gurus for further scrutiny.

**Comment by sethzenz** [comment]
This is being dealt with in CMSSW, Cf. https://github.com/cms-sw/cmssw/pull/10592, so we do not need to take any action in flashgg.  We'll need to update the CMSSW version to get the benefit, of course, but we're not (yet) space-starved.
