### ISSUE TITLE
Keep the link between the photon collection and photons stored into the diphoton object

### ISSUE THREAD

**Issue by OlivierBondu** [cms-analysis/flashgg#27]

**Comment by musella** [comment]
This should be straightforward to do with ShallowClones.

https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookParticleCandidates#ShallowCloneCands

**Comment by sethzenz** [comment]
I've been looking at the ShallowClone solution, but I think there's a problem: we attach flashgg-specific information at the same time we make the new objects:

https://github.com/cms-analysis/flashgg/blob/7bbbf7a03cd172cbdc2ea6ce80d51efdb7ed4826/MicroAOD/plugins/DiPhotonProducer.cc#L105-L108

Is there a way to salvage this approach, or should we just put a reference back to the originals (if available), to go alongside our copies?

**Comment by OlivierBondu** [comment]
as stated on the comment above the lines you quote, this information was needed for the preselection. The preselection, if we keep the current implementation using EDFilter (see https://github.com/cms-analysis/flashgg/blob/master/MicroAOD/python/flashggPreselectedDiPhotons_cfi.py), needs these in the photon candidate itself.

**Comment by sethzenz** [comment]
So my conclusion is that it's easiest to simply put a ref to the original photons into diphoton separately.  Make sense, @OlivierBondu and @musella?

**Comment by sethzenz** [comment]
Finally addressed by #251
