### ISSUE TITLE
Code does not compile

### ISSUE THREAD

**Issue by andreypz** [cms-analysis/flashgg#300]
Hi,
Trying to compile the code following instructions in README.
Get an error in JetProducer.cc:85:137: 
```
error: no matching function for call to 'PileupJetIdAlgo::computeIdVariables(const pat::Jet*, edm::Ptr<reco::Vertex>&, const std::vector<std::pair<edm::Ptr<reco::Vertex>, edm::Ptr<pat::PackedCandidate> > >&, bool)'
PileupJetIdentifier lPUJetId = pileupJetIdAlgo_->computeIdVariables( pjet.get(), vtx, *vertexCandidateMap, true );
```
Perhaps you can suggest a tag to checkout, instead of compiling the master branch?

**Comment by andreypz** [comment]
Never mind!
I found the tag name on the twiki, and now it compiles.
I think you should link the twiki page in the readme file.

**Comment by sethzenz** [comment]
Hi @andreypz, how did you initially set up flashgg?  Did you follow the instructions on the TWiki?  They include running the setup.sh script, which gets all the needed tags.  You can see the list here:

https://github.com/cms-analysis/flashgg/blob/master/setup.sh

**Comment by andreypz** [comment]
Hi,
Initially I simply copy-and-pasted commands from README.md, which does include running setup.sh 
But those instructions do not include ```git checkout Spring15BetaV2_MetaV3```, which is on the twiki.

**Comment by sethzenz** [comment]
Yes, but you don't need that tag for the code to successfully compile.  We always check that the current master compiles fine and is consistent with its own setup.sh.  If you fully followed the README.md instructions for any commit and can reproduce your error, please let me know.
