### ISSUE TITLE
Indentation pre-commit hook ignores git index

### ISSUE THREAD

**Issue by musella** [cms-analysis/flashgg#303]
Therefore it complains about files which are not being committed.

In other words: immagine that two files, A.c and B.c, have been modified. Also, immagine that A.c fulfills the indentation rules, but B.c doesn't.
The user is not allowed, at the moment, to commit A.c without fixing the indentation of B.c, which may be rather annoying in some cases.

**Comment by sethzenz** [comment]
In the future I agree it would be good to make the indent check smarter.  For now one can skip the check by doing:

    git commit --no-verify

**Comment by musella** [comment]
This is not yet fixed unfortunately.

The begin of line spaces should not be ignored, as they mark the difference between files in the index (ie staged to be committed) and files modified only in the work tree.

` M` means `modified but not in the index`
`M ` means `modified but and in the index`
