### ISSUE TITLE
eosimport can't guess the dataset names

### ISSUE THREAD

**Issue by andreypz** [cms-analysis/flashgg#317]
I found that there is a functionalyti to make datasets JSON file from eos, for example:
```fggManageSamples.py eosimport /store/group/phys_higgs/resonant_HH/RunII/MicroAOD/flashgg/RunIISpring15DR74/RunIISpring15MicroAODV1/GluGluToBulkGravitonToHHTo2B2G_M-260_narrow_13TeV-madgraph```
It is useful when the data is not published to DAS. However the script can't guess the name of the dataset, really. 
It also took me a while to realize that when inserted manually, it requires three-tier level name (/prim/sec/bla).  Suggestion: don't try to guess, instead clarify say in print out statement what kind of name is expected.

**Comment by sethzenz** [comment]
Related to #161. We are generally missing good error checking.  Raising issues is the right thing to do and is appreciated.   

I can't promise that we will quickly have manpower from the Hgg analysis available to act on these issues in the python scripts.   If you find a bug in python and know how to fix it quickly, you are also welcome to make a branch with the change and make a PR.

**Comment by musella** [comment]
This is not really a bad error check.

By default the code asks the user for the dataset name. If the user asks for the dataset name to be guessed, the it tries and asks again the user for confirmation.

The _can_ guess the dataset name, but only if the folder structure is crab3-like.

Concerning the three level structure it can be added to the dialog message, even though this is the default convention in CMS.
