### ISSUE TITLE
Appending the cross_section.json file

### ISSUE THREAD

**Issue by andreypz** [cms-analysis/flashgg#318]
From what I understand, there is a functionality to add an additional json file with cross sections.
I do it like this:
```
from flashgg.MetaData.JobConfig import customize
customize.crossSections.append("$CMSSW_BASE/src/APZ/fgg-ana/cross_sections.json")
```
However, this does not seem to work.
Any suggestions?

Also, would be nice to have this functionality for datasets.json (ie. to append another json file). It looks like this is not supported in the current scripts.

**Comment by andreypz** [comment]
Ok, appending cross section actually works!
The problem was that the names of the datasets did not match due to the issue in #317 

A request for implement the same thing for datasets.json is stil valid. Would be useful for the samples produced privately and not included in the main campaign (like our signals samples for HHbbgg).

**Comment by musella** [comment]
Datasets can already be added to existing catalogs upon running the import command several times.

Notes were explicitly added to  MetaData/README.md.
