### ISSUE TITLE
Add option for extra pyconfig params for fggRunJobs.py 

### ISSUE THREAD

**Issue by sethzenz** [cms-analysis/flashgg#352]
In some cases it's useful to do a batch submission for MicroAOD in which every job has a non-standard customization (e.g. puppi=1).  It should be possible to add these arguments when fggRunJobs.py is submitted, and as far as I can tell this is not currently possible. (@musella, is that right?)   

The most sensible way I can see to add this feature would be to have an --extraPyCfg argument to fggRunJobs.py, which would allow arbitrary customization options to be listed.

**Comment by musella** [comment]
It's already implemented.

See
https://github.com/cms-analysis/flashgg/tree/master/MetaData#per-dataset-specific-options

P.


On 23 September 2015 at 14:53, Seth Zenz <notifications@github.com> wrote:

> In some cases it's useful to do a batch submission for MicroAOD in which
> every job has a non-standard customization (e.g. puppi=1). It should be
> possible to add these arguments when fggRunJobs.py is submitted, and as far
> as I can tell this is not currently possible. (@musella
> <https://github.com/musella>, is that right?)
>
> The most sensible way I can see to add this feature would be to have an
> --extraPyCfg argument to fggRunJobs.py, which would allow arbitrary
> customization options to be listed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-analysis/flashgg/issues/352>.
>



-- 
Pasquale Musella - ETHZ
http://musella.web.cern.ch/musella

**Comment by sethzenz** [comment]
Sorry if I wasn't clear, but what I'm asking about is actually the other way around.  We want to be able to specify an extra option for all the jobs in a single place - probably on the command line, but a json file might be ok too as long as we don't have to repeat.

**Comment by musella** [comment]
Not sure I understand. Any option can be specified on the command line

fggRunJobs.py --load config.json -c cmsRun mypset.py option1=a option2=b ...



On 23 September 2015 at 15:20, Seth Zenz <notifications@github.com> wrote:

> Sorry if I wasn't clear, but what I'm asking about is actually the other
> way around. We want to be able to specify an extra option for all the jobs
> in a single place - probably on the command line, but a json file might be
> ok too as long as we don't have to repeat.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-analysis/flashgg/issues/352#issuecomment-142597345>
> .
>



-- 
Pasquale Musella - ETHZ
http://musella.web.cern.ch/musella

**Comment by sethzenz** [comment]
OK, this is useful, but I wrote slightly the wrong thing.  We were looking for the ability to do this in fggPrepareJobs.py (cf. PR #353 by @yhaddad). Is there already a way to do it there too?
