### ISSUE TITLE
PDFWeightsHelper not found

### ISSUE THREAD

**Issue by vtavolar** [cms-analysis/flashgg#461]
Hi all,

I tried to compile the head of the master branch but I got stuck with this error

/afs/cern.ch/work/v/vtavolar/Flashgg/CMSSW_7_4_15/src/flashgg/MicroAOD/plugins/PDFWeightObjectProducer.cc:19:68: fatal error: PhysicsTools/HepMCCandAlgos/interface/PDFWeightsHelper.
h: No such file or directory
 #include "PhysicsTools/HepMCCandAlgos/interface/PDFWeightsHelper.h"
                                                                    ^
compilation terminated.

I looked for this header in the cmssw repository but I couldn't find it in 7_4_X nor in 7_6_X.

Does anybody have suggestions on this? Am I missing something?

Thanks for your help,
Vittorio

**Comment by sethzenz** [comment]
Hi Vittorio,

flashgg/setup.sh has changed.  These lines were added:

https://github.com/cms-analysis/flashgg/blob/master/setup.sh#L113-L114

If you are running the master version in a fresh area, you should simply
need to do:

cd $CMSSW_BASE/src
git-cms-merge-topic bendavid:pdfweights_74x

and rebuild.

Seth

**Comment by vtavolar** [comment]
Hi Seth,

thanks a lot, this indeed fixed the problem.

Bests,
Vittorio
