### ISSUE TITLE
sigmaE/E smearing switched ON twice for data

### ISSUE THREAD

**Issue by vtavolar** [cms-analysis/flashgg#575]
Hi all,
I think this line 
https://github.com/cms-analysis/flashgg/blob/master/Systematics/python/SystematicsCustomize.py#L132
is responsible for switching ON a second time the sigmaE/E smearing in data systematics configuration. I would consider it a bug, am I missing something?

Thanks,
Vittorio

**Comment by sethzenz** [comment]
Yes I think you are right
