### ISSUE TITLE
fggRunJobs.py --cont fails when --stage-to is not specified

### ISSUE THREAD

**Issue by andreh7** [cms-analysis/flashgg#628]
with a stack trace similar to the following (line numbers may not be accurate):

```
Traceback (most recent call last):
  File ".../CMSSW_7_6_3_patch2/bin/slc6_amd64_gcc493/fggRunJobs.py", line 7, in <module>
    run()
  File ".../CMSSW_7_6_3_patch2/python/flashgg/MetaData/jobs_utils.py", line 157, in __call__
    self.loadLsfMon()
  File ".../CMSSW_7_6_3_patch2/python/flashgg/MetaData/jobs_utils.py", line 197, in loadLsfMon
    self.parallel.addJob(cmd,args,batchId,jobName)
  File ".../CMSSW_7_6_3_patch2/python/flashgg/MetaData/parallel.py", line 868, in addJob
    job = self.JobDriver(self.lsfQueue,jobName,async=True)
  File ".../CMSSW_7_6_3_patch2/python/flashgg/MetaData/parallel.py", line 455, in __call__
    stage_cmd = self.getStageCmd()
  File ".../CMSSW_7_6_3_patch2/python/flashgg/MetaData/parallel.py", line 441, in getStageCmd
    if self.stage_dest.startswith("/store"):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

A potential fix would be to also store `stage_dest` in `<output_dir>/task_config.json`, let me know if that would be the recommended way of fixing this.

**Comment by musella** [comment]
Ciao,

the place to store it should be config.json

P.


On 11 May 2016 at 10:01, andreh7 <notifications@github.com> wrote:

> with a stack trace similar to the following (line numbers may not be
> accurate):
>
> Traceback (most recent call last):
>   File ".../CMSSW_7_6_3_patch2/bin/slc6_amd64_gcc493/fggRunJobs.py", line 7, in <module>
>     run()
>   File ".../CMSSW_7_6_3_patch2/python/flashgg/MetaData/jobs_utils.py", line 157, in __call__
>     self.loadLsfMon()
>   File ".../CMSSW_7_6_3_patch2/python/flashgg/MetaData/jobs_utils.py", line 197, in loadLsfMon
>     self.parallel.addJob(cmd,args,batchId,jobName)
>   File ".../CMSSW_7_6_3_patch2/python/flashgg/MetaData/parallel.py", line 868, in addJob
>     job = self.JobDriver(self.lsfQueue,jobName,async=True)
>   File ".../CMSSW_7_6_3_patch2/python/flashgg/MetaData/parallel.py", line 455, in __call__
>     stage_cmd = self.getStageCmd()
>   File ".../CMSSW_7_6_3_patch2/python/flashgg/MetaData/parallel.py", line 441, in getStageCmd
>     if self.stage_dest.startswith("/store"):
> AttributeError: 'NoneType' object has no attribute 'startswith'
>
> A potential fix would be to also store stage_dest in
> <output_dir>/task_config.json, let me know if that would be the
> recommended way of fixing this.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-analysis/flashgg/issues/628>
>



-- 
Pasquale Musella - ETHZ
http://musella.web.cern.ch/musella
