### ISSUE TITLE
Keep all vertexes info in VertexSelector

### ISSUE THREAD

**Issue by musella** [cms-analysis/flashgg#64]
In order to be able to perform a training of the vertex selection algorithm, the information about all vertexes should be stored in the DiPhoton candidates.

For space reasons, one could limit the total number of vertexes to be stored, but the functionalities of the algorithms and the data format need to be extended.

**Comment by sethzenz** [comment]
Is this issue fully addressed by #102, #115, and #117   Can I close it?

**Comment by malcles** [comment]
Hello Seth,

yes I think it’s OK.

Julie
