### ISSUE TITLE
fggManageSamples.py needs das_client.py supporting authentication

### ISSUE THREAD

**Issue by andreh7** [cms-analysis/flashgg#752]
Since a few days, DAS requires authentication to read the information (see e.g. cernCompAnnounce/1144/1.html on hypernews). 

This can be achieved (assuming the user has a valid grid proxy) by adding the keyword arguments

`ckey=x509(), cert = x509()
`

to the calls to `das_query(..)` in MetaData/python/samples_utils.py (I can produce a pull request if desired). In fact, some commented out lines have these arguments already.

However the copy of das_client.py we have in MetaData/python/das_client.py does not support such authentication yet. We could either just remove it and rely on the one provided by the CMSSW environment or copy the latest version into the flashgg repository. 

The latter would have the advantage that it would also work with older CMSSW versions such as CMSSW_8_0_8_patch1 which points to das_client v02.05.00 which seems not to support authentication.

**Comment by andreh7** [comment]
in fact, it turns out that it is not necessary to update das_client.py in MetaData/python/ (MetaData/python/samples_utils.py has a copy of the function `x509(..)`) but adding the ckey and cert parameters in MetaData/python/samples_utils.py is.

**Comment by sethzenz** [comment]
Hi @andreh7 thanks for looking into this.  Can you make a PR with the needed changes?

Possibly also related: https://hypernews.cern.ch/HyperNews/CMS/get/comp-ops/3161/1.html
