### ISSUE TITLE
Vertex selection

### ISSUE THREAD

**Issue by andreypz** [cms-analysis/flashgg#760]
Hi,
For our analysis (HH -> bbgg) we would like to have **nvtx** (number of vertices) variable with some pre-selection. Specifically, we need to have the number of vertices that pass these:
```!isFake && ndof > 4 && abs(z) <= 24 && position.rho < 2``` which is *standard selection* in most other analysis. As far as I understand, such selection is not applied in flashgg [[1]]?
Would that be easy for you to create another variable, *nvtx2* with the mentioned selection, added in the same list of global variables?

UPD: There is a Vertex collection saved in MicroAOD, but it's not a  full collection right? So we couldn't get the needed number from there.  

Thanks,
Andrey

[1]: https://github.com/cms-analysis/flashgg/blob/63f87406b0c68300d3b9576e1e77ba1ddd89cf72/MicroAOD/src/GlobalVariablesComputer.cc#L149

**Comment by molmedon** [comment]
Hi Andrey,

you can create a filer in a similar way to flashgg diphotons are pre-selected which is applied after microAOD which contains the following vertex tag offlineSlimmedPrimaryVertices

https://github.com/cms-analysis/flashgg/blob/master/Taggers/python/flashggPreselectedDiPhotons_cfi.py
https://github.com/cms-analysis/flashgg/blob/6412a687b12c705ba7a1086c4b35ddda78839625/MicroAOD/plugins/DiPhotonCandidateSelector.cc#L64

If you are going to straight to flat trees, you can create a “dumper” the same way it is created to tag objects and the DiPhotonMVAResult class:

https://github.com/cms-analysis/flashgg/blob/63f87406b0c68300d3b9576e1e77ba1ddd89cf72/Taggers/plugins/EDDiPhotonMVAResultDumpers.cc
https://github.com/cms-analysis/flashgg/blob/63f87406b0c68300d3b9576e1e77ba1ddd89cf72/Taggers/interface/DiPhotonMVAResultDumper.h
https://github.com/cms-analysis/flashgg/blob/63f87406b0c68300d3b9576e1e77ba1ddd89cf72/Taggers/python/DiPhotonMVADumper_cff.py
https://github.com/cms-analysis/flashgg/blob/63f87406b0c68300d3b9576e1e77ba1ddd89cf72/Taggers/python/DiPhotonMVATrainingDumpConf_cff.py

which then you will need another file to run all the modules, and then apply the selection on our flat trees. Which way were you planning to go ? We can give more details, maybe someone can suggest a better way too.

cheers
Manuel




On Oct 5, 2016, at 8:30 AM, Andrey Pozdnyakov <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
For our analysis (HH -> bbgg) we would like to have nvtx (number of vertices) variable with some pre-selection. Specifically, we need to have the number of vertices that pass these:
!isFake && ndof > 4 && abs(z) <= 24 && position.rho < 2 which is standard selection in most other analysis. As far as I understand, such selection is not applied in flashgg [1<https://github.com/cms-analysis/flashgg/blob/63f87406b0c68300d3b9576e1e77ba1ddd89cf72/MicroAOD/src/GlobalVariablesComputer.cc#L149>]?
Would that be easy for you to create another variable, nvtx2 with the mentioned selection, added in the same list of global variables?

Thanks,
Andrey

**Comment by sethzenz** [comment]
The vertex collection is the standard one copied straight over from MiniAOD:

vector<reco::Vertex>                  "offlineSlimmedPrimaryVertices"   ""                "PAT"             

In general, anything labelled "PAT" is something copied over from the MiniAOD PAT algorithms without being touched by the Hgg code. You can read the MiniAOD documentation here:

https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookMiniAOD2016

You can certainly get the information you need from there.

**Comment by andreypz** [comment]
Ok, thank you.
Indeed we should be able to use the vertex collection from MicroAODs and apply the selection at the analysis level.
