### ISSUE TITLE
JEC path does not exist

### ISSUE THREAD

**Issue by vtavolar** [cms-analysis/flashgg#816]
Hello,
I think that after PR #806 the names of JEC .db and tag have changed and the suffix replacement at https://github.com/cms-analysis/flashgg/blob/master/Systematics/python/SystematicsCustomize.py#L188
fails now.
Can someone confirm this?
Bests,
Vittorio

**Comment by yhaddad** [comment]
I think this is still related to the name of the JEC.db files. There a small tweak that fixes that, please have a look on this PR #811. 

Best, 
Yacine

**Comment by vtavolar** [comment]
Thank you Yacine, I must have lost the fix during a rebase.
Bests,
Vittorio
