### ISSUE TITLE
Tab length

### ISSUE THREAD

**Issue by OlivierBondu** [cms-analysis/flashgg#83]
This annoys me regularly, so I am opening an issue, but feel free to close it if I am the only one in this case... One example of how this affect code readability would be [1]. 

Is there a way to agree on some common setting ? Like tab implemented as 4 spaces ? 

There used to be some settings like that in globe [2], but they are file-by-file, would anyone know a way to define them for the full repository ?

Cheers,
Olivier

[1] https://github.com/InnaKucher/flashgg/commit/e5b6f70808ef3c261af1d7fe8f01c4c73f83b797#diff-0
[2] https://github.com/h2gglobe/h2gglobe/blob/master/PhotonAnalysis/src/PhotonAnalysis.cc#L6902-L6908

**Comment by sethzenz** [comment]
Nothing new on this issue in a while.  I propose to adopt the convention of anyone who speaks up and is willing to set up vim + emacs configurations for whatever system/rule they like.  If nobody speaks up, I propose to close the issue and keep muddling through as we have.
