### ISSUE TITLE
Additional gen information

### ISSUE THREAD

**Issue by musella** [cms-analysis/flashgg#90]
Additional gen-level information should be kept. In particular:
- all hard process particles should be added to the flashggPrunedGenParticles.
- MC matching should be added to the photon producer.

**Comment by sethzenz** [comment]
Partially addressed by #126 and #144.  Still to-do: adding more to flashggPrunedGenParticles.

**Comment by sethzenz** [comment]
Rest is addressed by #148 so this can be closed as far as I know.  Please reopen if there's any part of this still undone.
