### ISSUE TITLE
Embed rechits in flashgg::Photon

### ISSUE THREAD

**Issue by musella** [cms-analysis/flashgg#91]
Some recHits should be embedded in the flashgg::Photons. 

The seed crystal recHit should be the very least. We may also consider to keep the full 5x5.

One potential issue with the 5x5 may be the data duplication in the photon and di-photon collections. It this becomes an issue, we could zero all the rechits except the seed just before copying to the di-photon object.

This is in fact a more general issue, related to the duplication of several variables which we inherit directly from the pat and reco photons.

**Comment by sethzenz** [comment]
@musella, is this addressed by #140?

**Comment by sethzenz** [comment]
Assuming this issue is now OK.  Please reopen if not.
