### ISSUE TITLE
Validation Code in flashgg

### ISSUE THREAD

**Issue by camilocarrillo** [cms-analysis/flashgg#92]
As mentioned during some of our flasgg meetings, would be nice to share the validation code we are using, I already did it with ours: https://github.com/cms-analysis/flashgg/blob/master/Commissioning/fwlite/plot_Vertex_ValidationFLASHgg.C I remember very nice plots from Inna and Francesca would be nice to be able to reproduce them!
Thanks!

**Comment by sethzenz** [comment]
@camilocarrillo, can you remind us concretely which plots you were requesting scripts for?  We do want everything related to validation in GitHub, but I don't want to keep this as an open issue.  So I'd like to either follow up on specific code that's needed or close this for now.
